export const SET_VISIBILITY_FILTER  = "SET_VISIBILITY_FILTER";

export const GET_CATEGORIES         = "GET_CATEGORIES";
export const GET_CATEGORIES_FATCHED = "GET_CATEGORIES_FATCHED";
export const GET_CATEGORIES_ERROR   = "GET_CATEGORIES_ERROR";

export const GET_PRODUCTS           = "GET_PRODUCTS";
export const GET_PRODUCTS_FATCHED   = "GET_PRODUCTS_FATCHED";
export const GET_PRODUCTS_ERROR     = "GET_PRODUCTS_ERROR";
